id: P006606
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18628
  title: དམངས་རྩོད་གཏུག་བཤེར་གྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    323151fa5f0a4c959243f99a8eb853d2:
      image_group_id: I8LS18630
      title: ''
      volume_number: 1
      total_pages: 305
      base_file: v001.txt
